"""V5 tools/v4_documents.py — Block T document-creation tools.

PORT_LOG: #103. ADR-038.

6 v4 document tools consolidated (one file, minimum-file constraint #5):
- create_word     — .docx via python-docx (lazy import).
- create_excel    — .xlsx via openpyxl (lazy import; supports chart_type).
- create_markdown — .md trivial write.
- create_notebook — .ipynb JSON shape.
- create_chart    — .png via matplotlib (lazy import; supports chart_type).
- create_pdf      — .pdf via matplotlib pdf backend (lazy import; supports
                    heading/text/table/image content blocks).

Each tool fails fast with a clear error if its underlying library is
missing. v5 doesn't pull these as hard dependencies (constraint #15) —
SageMaker users with the standard Python data-science kernel have all
of them installed.

Block T design note (test_tool_create_html_via_write_file_documented):
There is intentionally NO `create_html` tool. Use `write_file` with a
`.html` extension instead. HTML is text and `write_file` already works
for it; adding a separate tool is bloat.
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional

from .registry import build_tool, register


def _validate_doc_path(filepath: str):
    """Codex iter-2 CRITICAL fix: doc creators must validate-then-resolve
    via SECURITY.validate_path() (the actual gate), not _resolve_path()
    which is a path-join helper that does NOT enforce workspace bounds.

    Mirrors write_file's pattern at tools/write_file.py:79-83:
        ok, msg = path_security.validate_path(file_path)
        if not ok:
            return ...
        abs_path = os.path.abspath(path_security.resolve_path(file_path))

    Returns:
        (None, abs_path)  on success
        (error_str, None) on validation failure (out-of-workspace, sensitive)
    """
    try:
        from . import _path_validation as path_security
        from .artifacts import resolve_user_artifact_path
        filepath = resolve_user_artifact_path(filepath)
        ok, msg = path_security.validate_path(filepath)
        if not ok:
            return f"Error: {msg}", None
        abs_path = os.path.abspath(path_security.resolve_path(filepath))
        return None, abs_path
    except Exception as exc:  # noqa: BLE001
        return f"Error: path validation failed: {type(exc).__name__}: {exc}", None


def _ascii_contract_check(content: str, context: Optional[Dict] = None) -> str:
    try:
        from .artifacts import ascii_contract_error, is_ascii_only_request
        if is_ascii_only_request(context):
            return ascii_contract_error(content)
    except Exception:
        return ""
    return ""


def _record_created_artifact(abs_path: str, tool_name: str, context: Optional[Dict] = None) -> None:
    try:
        from .artifacts import record_artifact
        ctx = dict(context or {})
        ctx.setdefault("tool_name", tool_name)
        record_artifact(abs_path, kind="document", context=ctx)
    except Exception:
        pass


# ============================================================
# create_word — python-docx
# ============================================================

def _create_word_executor(args: Dict[str, Any], context: Optional[Dict] = None) -> str:
    filepath = str(args.get("filepath") or args.get("file_path") or "").strip()
    content = str(args.get("content") or "").strip()
    title = args.get("title")  # v4 advertised
    include_toc = bool(args.get("include_toc"))  # v4 advertised
    header = args.get("header")  # v4 advertised
    footer = args.get("footer")  # v4 advertised
    if not filepath:
        return "Error: filepath is required"
    if not filepath.endswith(".docx"):
        filepath += ".docx"
    err = _ascii_contract_check(content, context)
    if err:
        return err
    err, abs_path = _validate_doc_path(filepath)
    if err:
        return err
    try:
        from docx import Document
    except ImportError:
        return "Error: python-docx not installed; install via `pip install python-docx`"
    try:
        doc = Document()
        if title:
            doc.add_heading(str(title), level=0)
        if header:
            section = doc.sections[0]
            section.header.paragraphs[0].text = str(header)
        if footer:
            section = doc.sections[0]
            section.footer.paragraphs[0].text = str(footer)
        if include_toc:
            doc.add_paragraph("Table of Contents", style="Heading 1")
            doc.add_paragraph("(generated by Word — open in Word and update fields)")
        # Treat lines starting with `# ` as H1, `## ` as H2, etc.
        for line in content.splitlines():
            stripped = line.strip()
            if stripped.startswith("# "):
                doc.add_heading(stripped[2:], level=1)
            elif stripped.startswith("## "):
                doc.add_heading(stripped[3:], level=2)
            elif stripped.startswith("### "):
                doc.add_heading(stripped[4:], level=3)
            elif stripped:
                doc.add_paragraph(stripped)
            else:
                doc.add_paragraph("")
        os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
        doc.save(abs_path)
        _record_created_artifact(abs_path, "create_word", context)
        return f"Wrote {abs_path}"
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"


_CREATE_WORD_SCHEMA = {
    "type": "object",
    "properties": {
        "filepath": {"type": "string", "description": "Output .docx path."},
        "content": {"type": "string", "description": "Markdown-flavored content. # / ## / ### become Headings 1-3."},
        "title": {"type": "string", "description": "Optional document title (rendered as H0). v4 parity."},
        "include_toc": {"type": "boolean", "description": "Insert a TOC placeholder. v4 parity."},
        "header": {"type": "string", "description": "Optional page header text. v4 parity."},
        "footer": {"type": "string", "description": "Optional page footer text. v4 parity."},
    },
    "required": ["filepath", "content"],
}


# ============================================================
# create_excel — openpyxl
# ============================================================

def _create_excel_executor(args: Dict[str, Any], context: Optional[Dict] = None) -> str:
    filepath = str(args.get("filepath") or args.get("file_path") or "").strip()
    # Codex iter-1/2 HIGH: accept both v4 advertised `data` and v5 `rows`.
    has_data = args.get("data") is not None
    has_rows = args.get("rows") is not None
    raw_data = args.get("data") if has_data else args.get("rows")
    if raw_data is None:
        raw_data = []
    # Codex iter-3 MEDIUM: v4 required `data`. Reject empty payload instead
    # of silently writing an empty workbook.
    if not has_data and not has_rows:
        return "Error: data or rows is required (list of rows or list of dicts)"
    if not (isinstance(raw_data, list) and raw_data):
        return "Error: data/rows must be a non-empty list"
    chart_type = args.get("chart_type") or ""
    sheet_name = str(args.get("sheet_name") or "Sheet1")
    chart_title = args.get("chart_title")
    x_column = args.get("x_column")
    y_columns = args.get("y_columns") or []
    if not filepath:
        return "Error: filepath is required"
    if not filepath.endswith(".xlsx"):
        filepath += ".xlsx"
    err, abs_path = _validate_doc_path(filepath)
    if err:
        return err
    try:
        from openpyxl import Workbook
        from openpyxl.chart import BarChart, LineChart, PieChart, Reference
    except ImportError:
        return "Error: openpyxl not installed; install via `pip install openpyxl`"
    # Accept BOTH v4 shapes:
    # - rows = [[a, b], [c, d]] (list of lists; v5 added shape)
    # - data = [{"col": val, ...}, ...] (list of dicts; v4 advertised)
    rows: List[List[Any]] = []
    cols: List[str] = []
    if isinstance(raw_data, list) and raw_data:
        if isinstance(raw_data[0], dict):
            cols = list(raw_data[0].keys())
            rows.append(cols)
            for d in raw_data:
                rows.append([d.get(c, "") for c in cols])
        else:
            for row in raw_data:
                if isinstance(row, list):
                    rows.append(row)
                else:
                    rows.append([row])
            if rows:
                cols = [str(c) for c in rows[0]]
    try:
        wb = Workbook()
        ws = wb.active
        ws.title = sheet_name
        for row in rows:
            ws.append(row)
        if chart_type and len(rows) >= 2:
            chart_cls = {
                "bar": BarChart, "line": LineChart, "pie": PieChart,
            }.get(chart_type.lower(), BarChart)
            chart = chart_cls()
            if chart_title:
                chart.title = str(chart_title)
            # v4 column controls: x_column + y_columns name the columns to chart.
            if cols and x_column and y_columns:
                try:
                    x_idx = cols.index(x_column) + 1
                    for ycol in y_columns:
                        if ycol in cols:
                            y_idx = cols.index(ycol) + 1
                            yref = Reference(
                                ws, min_col=y_idx, min_row=1,
                                max_col=y_idx, max_row=len(rows),
                            )
                            chart.add_data(yref, titles_from_data=True)
                    cats = Reference(ws, min_col=x_idx, min_row=2, max_row=len(rows))
                    chart.set_categories(cats)
                except Exception:
                    # Fall back to whole-range chart if col-name lookup fails.
                    data_ref = Reference(
                        ws, min_col=1, min_row=1,
                        max_col=len(rows[0]) if rows else 1, max_row=len(rows),
                    )
                    chart.add_data(data_ref, titles_from_data=True)
            else:
                data_ref = Reference(
                    ws, min_col=1, min_row=1,
                    max_col=len(rows[0]) if rows else 1, max_row=len(rows),
                )
                chart.add_data(data_ref, titles_from_data=True)
            ws.add_chart(chart, "E2")
        os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
        wb.save(abs_path)
        return f"Wrote {abs_path}"
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"


_CREATE_EXCEL_SCHEMA = {
    "type": "object",
    "properties": {
        "filepath": {"type": "string"},
        # v4 advertised shape: list-of-dicts.
        "data": {
            "type": "array",
            "description": "List of dicts (v4 shape) or list of rows (v5 shape).",
        },
        # v5 alias for explicit row-of-rows callers.
        "rows": {
            "type": "array",
            "description": "List of rows; each row is a list of cell values (v5 alias for data).",
        },
        "sheet_name": {"type": "string", "description": "Worksheet name (v4 parity)."},
        "chart_type": {
            "type": "string", "enum": ["bar", "line", "pie"],
            "description": "Optional embedded chart type.",
        },
        "chart_title": {"type": "string", "description": "Title for the embedded chart (v4 parity)."},
        "x_column": {"type": "string", "description": "Column name to use as X axis (v4 parity)."},
        "y_columns": {
            "type": "array", "items": {"type": "string"},
            "description": "Column names to chart on Y axis (v4 parity).",
        },
    },
    "required": ["filepath"],
}


# ============================================================
# create_markdown — trivial
# ============================================================

def _create_markdown_executor(args: Dict[str, Any], context: Optional[Dict] = None) -> str:
    filepath = str(args.get("filepath") or args.get("file_path") or "").strip()
    content = str(args.get("content") or "")
    if not filepath:
        return "Error: filepath is required"
    if not filepath.endswith(".md"):
        filepath += ".md"
    err = _ascii_contract_check(content, context)
    if err:
        return err
    err, abs_path = _validate_doc_path(filepath)
    if err:
        return err
    try:
        os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as f:
            f.write(content)
        _record_created_artifact(abs_path, "create_markdown", context)
        return f"Wrote {abs_path}"
    except OSError as exc:
        return f"Error: {exc}"


_CREATE_MARKDOWN_SCHEMA = {
    "type": "object",
    "properties": {
        "filepath": {"type": "string"},
        "content": {"type": "string"},
    },
    "required": ["filepath", "content"],
}


# ============================================================
# create_notebook — JSON .ipynb format
# ============================================================

def _create_notebook_executor(args: Dict[str, Any], context: Optional[Dict] = None) -> str:
    filepath = str(args.get("filepath") or args.get("file_path") or "").strip()
    cells = args.get("cells") or []
    if not filepath:
        return "Error: filepath is required"
    if not filepath.endswith(".ipynb"):
        filepath += ".ipynb"
    err = _ascii_contract_check(json.dumps(cells, ensure_ascii=False, default=str), context)
    if err:
        return err
    err, abs_path = _validate_doc_path(filepath)
    if err:
        return err
    try:
        nb_cells = []
        for c in cells:
            if isinstance(c, dict):
                cell_type = c.get("type", "code")
                source = c.get("source", "")
                if isinstance(source, str):
                    source_lines = source.splitlines(keepends=True)
                else:
                    source_lines = list(source) if isinstance(source, list) else [str(source)]
                cell = {
                    "cell_type": cell_type,
                    "metadata": {},
                    "source": source_lines,
                }
                if cell_type == "code":
                    cell["execution_count"] = None
                    cell["outputs"] = []
                nb_cells.append(cell)
            elif isinstance(c, str):
                nb_cells.append({
                    "cell_type": "code",
                    "metadata": {},
                    "source": c.splitlines(keepends=True),
                    "execution_count": None,
                    "outputs": [],
                })
        notebook = {
            "cells": nb_cells,
            "metadata": {
                "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                "language_info": {"name": "python", "version": "3.11"},
            },
            "nbformat": 4,
            "nbformat_minor": 5,
        }
        os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as f:
            json.dump(notebook, f, indent=2)
        _record_created_artifact(abs_path, "create_notebook", context)
        return f"Wrote {abs_path}"
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"


_CREATE_NOTEBOOK_SCHEMA = {
    "type": "object",
    "properties": {
        "filepath": {"type": "string"},
        "cells": {"type": "array", "description": "List of cells. Each cell: {type: code|markdown, source: text}."},
    },
    "required": ["filepath", "cells"],
}


# ============================================================
# create_chart — matplotlib .png
# ============================================================

_CHART_TYPES_V4 = (
    "bar", "grouped_bar", "stacked_bar", "line", "pie",
    "scatter", "horizontal_bar", "combo",
)


def _create_chart_executor(args: Dict[str, Any], context: Optional[Dict] = None) -> str:
    filepath = str(args.get("filepath") or args.get("file_path") or "").strip()
    chart_type = (args.get("chart_type") or "bar").lower()
    data = args.get("data")
    title = args.get("title") or ""
    xlabel = args.get("xlabel")
    ylabel = args.get("ylabel")
    colors = args.get("colors") or None
    dpi = args.get("dpi")
    width = args.get("width")
    height = args.get("height")
    style = args.get("style")
    # Codex iter-3 MEDIUM: v4 required `data`. Reject missing payload.
    if data is None:
        return "Error: data is required ({labels:[],values:[]} or {x:[],y:[]} or {labels:[],series:[{name,values}]})"
    # Codex iter-4 HIGH fix: v4 defaults filepath to "chart.png" when omitted
    # (sagemaker_agent.py:6049-6052; schema required=[data]).
    if not filepath:
        filepath = "chart.png"
    if not filepath.endswith(".png"):
        filepath += ".png"
    err, abs_path = _validate_doc_path(filepath)
    if err:
        return err
    try:
        import matplotlib
        matplotlib.use("Agg")  # non-interactive backend for SageMaker
        import matplotlib.pyplot as plt
    except ImportError:
        return "Error: matplotlib not installed; install via `pip install matplotlib`"
    try:
        if style:
            try:
                plt.style.use(str(style))
            except Exception:
                pass  # silently fall back to default style on bad name
        # Codex iter-1/3 HIGH: accept v4 shapes:
        # - {label: value} (v5 dict shape)
        # - {labels: [...], values: [...]} (v4 simple shape)
        # - {x: [...], y: [...]} (v4 scatter shape)
        # - {labels: [...], series: [{name, values}, ...]} (v4 grouped/stacked/combo)
        labels: List[Any] = []
        values: List[Any] = []
        x_vals: List[Any] = []
        y_vals: List[Any] = []
        series: List[Dict[str, Any]] = []
        if isinstance(data, dict):
            if "x" in data and "y" in data:
                x_vals = list(data.get("x") or [])
                y_vals = list(data.get("y") or [])
                labels = [str(x) for x in x_vals]
                values = list(y_vals)
            elif "labels" in data and "series" in data:
                labels = list(data.get("labels") or [])
                series_raw = data.get("series") or []
                series = [
                    {"name": str(s.get("name") or f"series{i}"),
                     "values": list(s.get("values") or [])}
                    for i, s in enumerate(series_raw) if isinstance(s, dict)
                ]
                if series:
                    values = series[0]["values"]
            elif "labels" in data and "values" in data:
                labels = list(data.get("labels") or [])
                values = list(data.get("values") or [])
            elif "labels" in data and ("bar_values" in data or "line_values" in data):
                # Codex iter-5 MEDIUM fix: v4 combo shape
                # {labels, bar_values, line_values, ...} must NOT fall through
                # to the generic dict-keys path (which would set labels =
                # ["labels", "bar_values", ...]). Set labels + values from
                # explicit fields; the combo branch later reads bar/line vals.
                labels = list(data.get("labels") or [])
                values = list(data.get("bar_values") or data.get("line_values") or [])
            else:
                labels = list(data.keys())
                values = list(data.values())
        fig_kwargs: Dict[str, Any] = {}
        if width and height:
            try:
                fig_kwargs["figsize"] = (float(width), float(height))
            except Exception:
                pass
        fig, ax = plt.subplots(**fig_kwargs)
        n_labels = len(labels)
        # Render based on chart type.
        if chart_type == "line":
            if series:
                for s in series:
                    ax.plot(labels[:len(s["values"])], s["values"], label=s["name"])
                ax.legend()
            else:
                ax.plot(labels, values, color=(colors[0] if colors else None))
        elif chart_type == "pie":
            ax.pie(values, labels=labels, colors=colors)
        elif chart_type == "scatter":
            ax.scatter(x_vals or labels, y_vals or values,
                       c=(colors[0] if colors else None))
        elif chart_type == "horizontal_bar":
            ax.barh(labels, values, color=colors)
        elif chart_type == "grouped_bar" and series:
            # Grouped bar: each series is one bar per label, offset within group.
            try:
                import numpy as np  # numpy ships with matplotlib
                x = np.arange(n_labels)
                width_per = 0.8 / max(1, len(series))
                for i, s in enumerate(series):
                    ax.bar(x + i * width_per, s["values"], width_per,
                           label=s["name"],
                           color=(colors[i] if colors and i < len(colors) else None))
                ax.set_xticks(x + width_per * (len(series) - 1) / 2)
                ax.set_xticklabels(labels)
                ax.legend()
            except Exception:
                ax.bar(labels, values, color=colors)
        elif chart_type == "stacked_bar" and series:
            try:
                bottom = [0.0] * n_labels
                for i, s in enumerate(series):
                    vals = list(s["values"]) + [0] * max(0, n_labels - len(s["values"]))
                    ax.bar(labels, vals[:n_labels], bottom=bottom, label=s["name"],
                           color=(colors[i] if colors and i < len(colors) else None))
                    bottom = [b + v for b, v in zip(bottom, vals[:n_labels])]
                ax.legend()
            except Exception:
                ax.bar(labels, values, color=colors)
        elif chart_type == "combo":
            # Codex iter-4 MEDIUM fix: v4 combo shape is
            # {labels, bar_values, line_values, bar_label, line_label, line_ylabel}
            # (sagemaker_agent.py:6194-6214). Support v4 shape first;
            # fall back to series-based combo if data uses {labels, series}.
            try:
                if isinstance(data, dict) and "bar_values" in data and "line_values" in data:
                    bar_values = list(data.get("bar_values") or [])
                    line_values = list(data.get("line_values") or [])
                    bar_label = str(data.get("bar_label") or "Bar")
                    line_label = str(data.get("line_label") or "Line")
                    line_ylabel = data.get("line_ylabel")
                    n = min(len(labels), len(bar_values))
                    ax.bar(labels[:n], bar_values[:n], label=bar_label,
                           color=(colors[0] if colors else None))
                    if line_ylabel:
                        ax2 = ax.twinx()
                        ax2.set_ylabel(str(line_ylabel))
                        ax2.plot(labels[:len(line_values)], line_values, label=line_label,
                                 color=(colors[1] if colors and len(colors) > 1 else "tab:orange"))
                        ax2.legend(loc="upper right")
                    else:
                        ax.plot(labels[:len(line_values)], line_values, label=line_label,
                                color=(colors[1] if colors and len(colors) > 1 else "tab:orange"))
                    ax.legend(loc="upper left")
                elif series:
                    # series-based combo: first series as bar, rest as line.
                    first = series[0]
                    ax.bar(labels[:len(first["values"])], first["values"], label=first["name"],
                           color=(colors[0] if colors else None))
                    for i, s in enumerate(series[1:], start=1):
                        ax.plot(labels[:len(s["values"])], s["values"], label=s["name"],
                                color=(colors[i] if colors and i < len(colors) else None))
                    ax.legend()
                else:
                    ax.bar(labels, values, color=colors)
            except Exception:
                ax.bar(labels, values, color=colors)
        else:  # bar (default + fallback)
            ax.bar(labels, values, color=colors)
        if title:
            ax.set_title(title)
        if xlabel:
            ax.set_xlabel(str(xlabel))
        if ylabel:
            ax.set_ylabel(str(ylabel))
        os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
        save_kwargs: Dict[str, Any] = {}
        if dpi:
            try:
                save_kwargs["dpi"] = int(dpi)
            except Exception:
                pass
        fig.savefig(abs_path, **save_kwargs)
        plt.close(fig)
        _record_created_artifact(abs_path, "create_chart", context)
        return f"Wrote {abs_path}"
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"


_CREATE_CHART_SCHEMA = {
    "type": "object",
    "properties": {
        "filepath": {"type": "string"},
        "chart_type": {
            "type": "string",
            "enum": list(_CHART_TYPES_V4),
            "default": "bar",
            "description": "v4 advertised chart types: bar, grouped_bar, stacked_bar, line, pie, scatter, horizontal_bar, combo.",
        },
        "data": {
            "type": "object",
            "description": "Required. Shapes: {labels:[],values:[]} or {x:[],y:[]} or {labels:[],series:[{name,values}]}",
        },
        "title": {"type": "string"},
        "xlabel": {"type": "string", "description": "X-axis label (v4 parity)."},
        "ylabel": {"type": "string", "description": "Y-axis label (v4 parity)."},
        "colors": {
            "type": "array", "items": {"type": "string"},
            "description": "Per-series/bar colors (v4 parity).",
        },
        "dpi": {"type": "integer", "description": "Resolution in DPI; use 150 for reports (v4 parity)."},
        "width": {"type": "number", "description": "Figure width in inches (v4 parity)."},
        "height": {"type": "number", "description": "Figure height in inches (v4 parity)."},
        "style": {"type": "string", "description": "matplotlib style name (v4 parity)."},
    },
    "required": ["data"],
}


# ============================================================
# create_pdf — matplotlib pdf backend with content blocks
# ============================================================

_PAGE_SIZES = {
    # (width, height) in inches.
    "letter": (8.5, 11),
    "a4": (8.27, 11.69),
    "legal": (8.5, 14),
}


def _create_pdf_executor(args: Dict[str, Any], context: Optional[Dict] = None) -> str:
    filepath = str(args.get("filepath") or args.get("file_path") or "").strip()
    # Codex iter-2 HIGH: accept v4 `data` AND v5 `content` for the block list.
    has_data = args.get("data") is not None
    has_content = args.get("content") is not None
    content_blocks = args.get("data") if has_data else args.get("content")
    if content_blocks is None:
        content_blocks = []
    # Codex iter-3 MEDIUM: v4 required `content`. Reject empty payload
    # instead of silently writing a blank PDF.
    if not has_data and not has_content:
        return "Error: data or content is required (list of blocks)"
    if not (isinstance(content_blocks, list) and content_blocks):
        return "Error: data/content must be a non-empty list of blocks"
    doc_title = args.get("title")
    page_size = str(args.get("page_size") or "letter").lower()
    if not filepath:
        return "Error: filepath is required"
    if not filepath.endswith(".pdf"):
        filepath += ".pdf"
    err = _ascii_contract_check(json.dumps(content_blocks, ensure_ascii=False, default=str), context)
    if err:
        return err
    err, abs_path = _validate_doc_path(filepath)
    if err:
        return err
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from matplotlib.backends.backend_pdf import PdfPages
    except ImportError:
        return "Error: matplotlib not installed (PDF backend); install via `pip install matplotlib`"
    fig_size = _PAGE_SIZES.get(page_size, _PAGE_SIZES["letter"])
    try:
        os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
        with PdfPages(abs_path) as pdf:
            fig = plt.figure(figsize=fig_size)
            ax = fig.add_subplot(111)
            ax.axis("off")
            y = 0.95
            if doc_title:
                ax.text(0.05, y, str(doc_title), fontsize=22, fontweight="bold")
                y -= 0.08
            for block in (content_blocks if isinstance(content_blocks, list) else []):
                if not isinstance(block, dict):
                    continue
                btype = block.get("type", "text")
                # v4 per-block field is `data`; v5 originally used type-specific fields.
                # Support BOTH: `text`, `rows`, AND v4 `data`.
                bdata = block.get("data")
                btext = str(block.get("text") or (bdata if isinstance(bdata, str) else ""))
                if btype == "heading":
                    ax.text(0.05, y, btext, fontsize=18, fontweight="bold")
                    y -= 0.06
                elif btype == "text":
                    ax.text(0.05, y, btext, fontsize=10, wrap=True)
                    y -= 0.04
                elif btype == "table":
                    rows = block.get("rows") or (bdata if isinstance(bdata, list) else [])
                    for row in rows:
                        ax.text(0.05, y, " | ".join(str(c) for c in (row if isinstance(row, list) else [row])), fontsize=9, family="monospace")
                        y -= 0.03
                elif btype == "image":
                    img_ref = btext or (str(bdata) if bdata else "")
                    ax.text(0.05, y, f"[image: {img_ref}]", fontsize=10, style="italic")
                    y -= 0.04
                if y < 0.1:
                    pdf.savefig(fig)
                    plt.close(fig)
                    fig = plt.figure(figsize=fig_size)
                    ax = fig.add_subplot(111)
                    ax.axis("off")
                    y = 0.95
            pdf.savefig(fig)
            plt.close(fig)
        _record_created_artifact(abs_path, "create_pdf", context)
        return f"Wrote {abs_path}"
    except Exception as exc:  # noqa: BLE001
        return f"Error: {type(exc).__name__}: {exc}"


_CREATE_PDF_SCHEMA = {
    "type": "object",
    "properties": {
        "filepath": {"type": "string"},
        # v4 advertised field: `data`.
        "data": {
            "type": "array",
            "description": "Content blocks (v4 shape): [{type: heading|text|table|image, data: ...}]",
        },
        # v5 alias.
        "content": {
            "type": "array",
            "description": "Content blocks (v5 alias for data): [{type, text|rows|...}]",
        },
        "title": {"type": "string", "description": "Optional document title (v4 parity)."},
        "page_size": {
            "type": "string", "enum": ["letter", "a4", "legal"],
            "description": "Page size (v4 parity). Default 'letter'.",
        },
    },
    "required": ["filepath"],
}


# ============================================================
# Registration
# ============================================================

_DOC_DESC = "Document creation tool — Block T (v4 surface parity)."


def _register():
    """Idempotent registration of all 6 document tools."""
    from .registry import find_tool_by_name, all_registered

    pairs = [
        ("create_word", _CREATE_WORD_SCHEMA, _create_word_executor,
         "Write a .docx file. Supports # / ## / ### markdown headings."),
        ("create_excel", _CREATE_EXCEL_SCHEMA, _create_excel_executor,
         "Write an .xlsx file. Supports embedded chart_type."),
        ("create_markdown", _CREATE_MARKDOWN_SCHEMA, _create_markdown_executor,
         "Write a .md file. Trivial wrapper over write_file with extension validation."),
        ("create_notebook", _CREATE_NOTEBOOK_SCHEMA, _create_notebook_executor,
         "Write an .ipynb file. cells = [{type: code|markdown, source: text}]."),
        ("create_chart", _CREATE_CHART_SCHEMA, _create_chart_executor,
         "Create chart PNG image. WHEN: generating visualizations for "
         "Word/PDF reports (create chart FIRST, then embed). Types: bar, "
         "grouped_bar, stacked_bar, line, pie, scatter, horizontal_bar, "
         "combo. Always set title, xlabel, ylabel for professional output. "
         "Use dpi=150 for reports."),
        ("create_pdf", _CREATE_PDF_SCHEMA, _create_pdf_executor,
         "Write a .pdf file via matplotlib. content = [{type: heading|text|table|image, ...}]."),
    ]
    for name, schema, executor, desc in pairs:
        if find_tool_by_name(all_registered(), name) is not None:
            continue
        register(build_tool(
            name=name,
            description=desc,
            input_schema=schema,
            execute=executor,
            requires_approval=True,
            should_defer=True,  # deferred-loading saves tokens
            max_result_size_chars=2000,
        ))
